services:
  db:
    image: postgres:16
    container_name: todo-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
      - PGTZ=Asia/Tokyo

volumes:
  postgres_data: